<?php
$MLBFEEDS = array(
array ('team' => 'Los Angeles Angels of Anaheim',   'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/ana.xml', 'league' => 'AL', 'code' => 'ANA'),
array ('team' => 'Oakland Athletics',               'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/oak.xml', 'league' => 'AL', 'code' => 'OAK'),
array ('team' => 'Toronto Blue Jays',               'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/tor.xml', 'league' => 'AL', 'code' => 'TOR'),
array ('team' => 'Tampa Bay Rays',                  'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/tb.xml',  'league' => 'AL', 'code' => 'TB'),
array ('team' => 'Cleveland Indians',               'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/cle.xml', 'league' => 'AL', 'code' => 'CLE'),
array ('team' => 'Seattle Mariners',                'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/sea.xml', 'league' => 'AL', 'code' => 'SEA'),
array ('team' => 'Baltimore Orioles',               'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/bal.xml', 'league' => 'AL', 'code' => 'BAL'),
array ('team' => 'Texas Rangers',                   'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/tex.xml', 'league' => 'AL', 'code' => 'TEX'),
array ('team' => 'Boston Red Sox',                  'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/bos.xml', 'league' => 'AL', 'code' => 'BOS'),
array ('team' => 'Kansas City Royals',              'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/kc.xml',  'league' => 'AL', 'code' => 'KC'),
array ('team' => 'Detroit Tigers',                  'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/det.xml', 'league' => 'AL', 'code' => 'DET'),
array ('team' => 'Minnesota Twins',                 'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/min.xml', 'league' => 'AL', 'code' => 'MIN'),
array ('team' => 'Chicago White Sox',               'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/cws.xml', 'league' => 'AL', 'code' => 'CWS'),
array ('team' => 'New York Yankees',                'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/nyy.xml', 'league' => 'AL', 'code' => 'NYY'),
array ('team' => 'Houston Astros',                  'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/hou.xml', 'league' => 'NL', 'code' => 'HOU'),
array ('team' => 'Atlanta Braves',                  'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/atl.xml', 'league' => 'NL', 'code' => 'ATL'),
array ('team' => 'Milwaukee Brewers',               'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/mil.xml', 'league' => 'NL', 'code' => 'MIL'),
array ('team' => 'St. Louis Cardinals',             'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/stl.xml', 'league' => 'NL', 'code' => 'STL'),
array ('team' => 'Chicago Cubs',                    'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/chc.xml', 'league' => 'NL', 'code' => 'CHC'),
array ('team' => 'Arizona Diamondbacks',            'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/ari.xml', 'league' => 'NL', 'code' => 'ARI'),
array ('team' => 'Los Angeles Dodgers',             'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/la.xml',  'league' => 'NL', 'code' => 'LA'),
array ('team' => 'San Francisco Giants',            'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/sf.xml',  'league' => 'NL', 'code' => 'SF'),
array ('team' => 'Florida Marlins',                 'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/fla.xml', 'league' => 'NL', 'code' => 'FLA'),
array ('team' => 'New York Mets',                   'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/nym.xml', 'league' => 'NL', 'code' => 'NYM'),
array ('team' => 'Washington Nationals',            'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/was.xml', 'league' => 'NL', 'code' => 'WAS'),
array ('team' => 'San Diego Padres',                'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/sd.xml',  'league' => 'NL', 'code' => 'SD'),
array ('team' => 'Philadelphia Phillies',           'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/phi.xml', 'league' => 'NL', 'code' => 'PHI'),
array ('team' => 'Pittsburgh Pirates',              'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/pit.xml', 'league' => 'NL', 'code' => 'PIT'),
array ('team' => 'Cincinnati Reds',                 'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/cin.xml', 'league' => 'NL', 'code' => 'CIN'),
array ('team' => 'Colorado Rockies',                'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/col.xml', 'league' => 'NL', 'code' => 'COL'),
array ('team' => 'Major League Baseball',           'feed' => 'http://mlb.mlb.com/partnerxml/gen/news/rss/mlb.xml', 'league' => '--', 'code' => 'MLB')
);
?>